{
 "title": "vCloud Director - Organization",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": "SHOW TAG VALUES FROM org WITH KEY = \"name\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Running VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfRunningVMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "oVCDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfVdcs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "vApps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfVApps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Catalogs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfCatalogs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Groups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfGroups" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuLimit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "vCPU  Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000/2.4" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "vCPU  Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuLimit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000/2.4" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityMemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityMemoryLimit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityMemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "UsedNetworkCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC-storage",
     "select": [
      [
       { "params": [ "StorageUsedMB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "org", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  }
 ]
}