{
 "title": "vCloud Director",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfRunningVMs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "oVCDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfVdcs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "vApps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfVApps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Catalogs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfCatalogs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfDisks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Groups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "org",
     "select": [
      [
       { "params": [ "numberOfGroups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuUsed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuLimit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vCPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuUsed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/2.4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vCPU Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuLimit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/2.4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityMemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1024*1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityMemoryLimit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1024*1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityCpuUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "IsEnabled", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC",
     "select": [
      [
       { "params": [ "ComputeCapacityMemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1024*1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "IsEnabled", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Poller Stats",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "poller",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Request Count" ], "type": "alias" }
      ],
      [
       { "params": [ "runtime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Runtime" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ovdc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ovdc" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oVDC-storage",
     "select": [
      [
       { "params": [ "StorageUsedMB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1024*1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Enabled", "operator": "=", "value": "true" }
     ]
    }
   ]
  }
 ]
}